Frontend/development/CSS-Files-Migration
bounswe/bounswe2023group4 pull request #330
Opened 2023-11-12 12:04 UTC by AliNasra

I have removed the CSS code from the jsx files of Sign-in and Sign-up pages. Nevertheless, there are a lot of errors that prevent the code from compiling properly.

2023-11-13 07:32 UTC, AliNasra commented
I have rectified the problems in general though there is a little anomaly with the Sign-Up page's UI,

2023-11-13 10:36 UTC, enfurars commented
What is the anomaly?

2023-11-14 12:13 UTC, selinisik requested changes

2023-11-14 12:13 UTC, selinisik commented on prediction-polls/frontend/src/Pages/Auth/SignIn/SignIn.module.css
> +  background: linear-gradient(var(--primary-900), var(--primary-800));
Sign-in page background color is not correct.

2023-11-14 12:15 UTC, enfurars requested changes
Button colors of the sign up page are not correct. Padding can be checked also.

2023-11-14 19:07 UTC, selinisik commented
Due to urgency, I fixed the errors in the PR!

2023-11-14 19:07 UTC, merged