Edit Profile for Mobile App
bounswe/bounswe2023group4 pull request #578
Opened 2023-12-18 20:53 UTC by aemresafak

I have implemented the edit profile screen, albeit being late for a week. I am very sorry about the delay. This PR concludes #512. Now users can edit their profiles.

2023-12-18 21:02 UTC, YigitSekerci requested changes
UI seems good in overall but you should connect this page to the backend. The backend is already implemented.

2023-12-18 21:02 UTC, YigitSekerci commented on prediction-polls/android/app/src/main/AndroidManifest.xml
> +        android:usesCleartextTraffic="true"
We need to think about this flag before the final milestone. Let's talk with BE team tomorrow.

2023-12-19 13:58 UTC, aemresafak commented
can you check again please yigit?

2023-12-19 14:00 UTC, YigitSekerci approved these changes
Helal Ahmettt devamkee

2023-12-19 14:00 UTC, YigitSekerci commented on prediction-polls/android/app/src/main/java/com/bounswe/predictionpolls/data/profile/model/ProfileInfoResponse.kt
> + */
Nice touch Ahmet

2023-12-19 14:00 UTC, merged